### ISSUE TITLE
support tagged docker releases

### ISSUE THREAD

**Issue by makohoek** [makohoek/repo-resource#22]
Right now, we solely push the docker images as `latest`. This is not super convenient for pipeline writers as they might hit regressions/problems each time we update `repo-resource`.

Implement some docker tagging/versioning within github actions here.

**Comment by DrummyFloyd** [comment]
you should insipire your pipeline with this 

https://github.com/marketplace/actions/docker-publish-semver-tags

**Comment by makohoek** [comment]
I think I'll just use https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub (which is the standard way) instead

**Comment by makohoek** [comment]
This is implemented.

First release is here:
https://github.com/makohoek/repo-resource/releases/tag/v1.0.0

Published on docker hub:
https://hub.docker.com/layers/mkorpershoek/repo-resource/v1.0.0/images/sha256-56a5d4eb784c7213c62599f0a7e6e683baf087ca8c2f10df9297e1dfdb7bc734?context=explore

Done via: https://github.com/makohoek/repo-resource/commit/9feec57ca79f0635c20aebdc5574087421d57fa4
